"""billing + advantasms models

Revision ID: 322a0a964239
Revises: ad4df2f515db
Create Date: 2025-12-16 10:46:24.542258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322a0a964239'
down_revision = 'ad4df2f515db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('partner_id', sa.String(length=60), nullable=True),
    sa.Column('api_key_hint', sa.String(length=64), nullable=True),
    sa.Column('api_key_last_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('default_shortcode', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_configs')),
    sa.UniqueConstraint('provider', name=op.f('uq_provider_configs_provider'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_api_keys_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('client_account_id', 'name', name='uq_apikey_name_per_client')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'void', 'overdue', name='invoice_status'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_invoices_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_no'), ['invoice_no'], unique=True)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sender_id_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id_id'], ['sender_ids.id'], name=op.f('fk_invoice_items_sender_id_id_sender_ids'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_invoice_items_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_sender_id_id'), ['sender_id_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'reversed', name='payment_status'), nullable=False),
    sa.Column('method', sa.Enum('mpesa', 'bank', 'cash', 'card', name='payment_method'), nullable=False),
    sa.Column('amount_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mpesa_receipt', sa.String(length=40), nullable=True),
    sa.Column('payer_phone', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_payments_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_mpesa_receipt'), ['mpesa_receipt'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.Enum('transactional', 'promotional', 'otp', name='campaign_message_type'), nullable=False))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('provider_batch_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('total_recipients',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_sent',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_failed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_campaigns_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index('ix_campaigns_client_status', ['client_account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_sender_id_id'), ['sender_id_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    with op.batch_alter_table('client_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cost_price_per_sms_kes', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('sell_price_per_sms_kes', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('default_shortcode', sa.String(length=20), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_e164', sa.String(length=20), nullable=True))
        batch_op.alter_column('is_opted_out',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_contacts_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index('ix_contacts_client_phone', ['client_account_id', 'phone'], unique=False)
        batch_op.create_index('ix_contacts_client_phonee164', ['client_account_id', 'phone_e164'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_phone_e164'), ['phone_e164'], unique=False)

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_units', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_payment_id'), ['payment_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_credit_transactions_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_credit_transactions_payment_id_payments'), 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('amount')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_groups_client', ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_unique_constraint('uq_group_name_per_client', ['client_account_id', 'name'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone_e164', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.Enum('transactional', 'promotional', 'otp', name='message_type'), nullable=False))
        batch_op.add_column(sa.Column('units', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sell_price_per_sms_kes_snapshot', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cost_price_per_sms_kes_snapshot', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('client_sms_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('provider_status', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('provider_response_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('provider_response_desc', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('network_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('callback_payload', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_messages_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_messages_campaign_status', ['campaign_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_client_sms_id'), ['client_sms_id'], unique=False)
        batch_op.create_index('ix_messages_client_status_created', ['client_account_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index('ix_messages_phone', ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_phone_e164'), ['phone_e164'], unique=False)
        batch_op.create_index('ix_messages_phonee164', ['phone_e164'], unique=False)
        batch_op.create_index('ix_messages_provider_id', ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)
        batch_op.create_index('ix_messages_type', ['client_account_id', 'message_type'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_messages_client_account_id_client_accounts'), 'client_accounts', ['client_account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('sender_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_setup_fee_kes', sa.Integer(), nullable=False))
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('safaricom_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('airtel_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('telkom_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('requested_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_sender_ids_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index('ix_sender_ids_client_status', ['client_account_id', 'status'], unique=False)
        batch_op.drop_column('setup_fee_kes')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_client_account_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_client_account_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('sender_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_fee_kes', sa.INTEGER(), nullable=True))
        batch_op.drop_index('ix_sender_ids_client_status')
        batch_op.drop_index(batch_op.f('ix_sender_ids_client_account_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('requested_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('telkom_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('airtel_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('safaricom_status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
        batch_op.drop_column('network_setup_fee_kes')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_client_account_id_client_accounts'), type_='foreignkey')
        batch_op.drop_index('ix_messages_type')
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_provider_message_id'))
        batch_op.drop_index('ix_messages_provider_id')
        batch_op.drop_index('ix_messages_phonee164')
        batch_op.drop_index(batch_op.f('ix_messages_phone_e164'))
        batch_op.drop_index('ix_messages_phone')
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_messages_contact_id'))
        batch_op.drop_index('ix_messages_client_status_created')
        batch_op.drop_index(batch_op.f('ix_messages_client_sms_id'))
        batch_op.drop_index(batch_op.f('ix_messages_client_account_id'))
        batch_op.drop_index('ix_messages_campaign_status')
        batch_op.drop_index(batch_op.f('ix_messages_campaign_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('callback_payload')
        batch_op.drop_column('network_id')
        batch_op.drop_column('provider_response_desc')
        batch_op.drop_column('provider_response_code')
        batch_op.drop_column('provider_status')
        batch_op.drop_column('client_sms_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('cost_price_per_sms_kes_snapshot')
        batch_op.drop_column('sell_price_per_sms_kes_snapshot')
        batch_op.drop_column('units')
        batch_op.drop_column('message_type')
        batch_op.drop_column('phone_e164')
        batch_op.drop_column('client_account_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('uq_group_name_per_client', type_='unique')
        batch_op.drop_index(batch_op.f('ix_groups_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_groups_client_account_id'))
        batch_op.drop_index('ix_groups_client')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_credit_transactions_payment_id_payments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_credit_transactions_invoice_id_invoices'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_credit_transactions_payment_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_client_account_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('amount_units')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_phone_e164'))
        batch_op.drop_index(batch_op.f('ix_contacts_created_by_user_id'))
        batch_op.drop_index('ix_contacts_client_phonee164')
        batch_op.drop_index('ix_contacts_client_phone')
        batch_op.drop_index(batch_op.f('ix_contacts_client_account_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_opted_out',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('phone_e164')

    with op.batch_alter_table('client_accounts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('default_shortcode')
        batch_op.drop_column('sell_price_per_sms_kes')
        batch_op.drop_column('cost_price_per_sms_kes')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_sender_id_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_message_type'))
        batch_op.drop_index(batch_op.f('ix_campaigns_created_by_user_id'))
        batch_op.drop_index('ix_campaigns_client_status')
        batch_op.drop_index(batch_op.f('ix_campaigns_client_account_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('total_failed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_sent',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_recipients',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('provider_batch_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('message_type')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_mpesa_receipt'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_client_account_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_sender_id_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_account_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_client_account_id'))

    op.drop_table('api_keys')
    op.drop_table('provider_configs')
    # ### end Alembic commands ###
