"""Make message campaign_id nullable

Revision ID: 4871d3fcee9c
Revises: 322a0a964239
Create Date: 2025-12-16 18:00:40.753184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4871d3fcee9c'
down_revision = '322a0a964239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
