"""initial multi-tenant schema

Revision ID: ad4df2f515db
Revises: 
Create Date: 2025-12-16 09:36:53.172404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4df2f515db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('primary_email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='client_account_status'), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_accounts'))
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('monthly_fee_kes', sa.Integer(), nullable=False),
    sa.Column('included_sms_units', sa.Integer(), nullable=False),
    sa.Column('overage_price_per_sms_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='plan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_plans_name'))
    )
    op.create_table('sender_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=11), nullable=False),
    sa.Column('purpose', sa.Enum('transactional', 'promotional', 'otp', name='sender_id_purpose'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='sender_id_status'), nullable=False),
    sa.Column('safaricom_status', sa.Enum('pending', 'approved', 'rejected', name='sid_safaricom_status'), nullable=True),
    sa.Column('airtel_status', sa.Enum('pending', 'approved', 'rejected', name='sid_airtel_status'), nullable=True),
    sa.Column('telkom_status', sa.Enum('pending', 'approved', 'rejected', name='sid_telkom_status'), nullable=True),
    sa.Column('setup_fee_kes', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_sender_ids_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sender_ids')),
    sa.UniqueConstraint('client_account_id', 'sender_id', name='uq_senderid_per_client')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'cancelled', name='subscription_status'), nullable=False),
    sa.Column('billing_start', sa.DateTime(), nullable=False),
    sa.Column('billing_end', sa.DateTime(), nullable=True),
    sa.Column('plan_name_snapshot', sa.String(length=80), nullable=True),
    sa.Column('monthly_fee_kes_snapshot', sa.Integer(), nullable=True),
    sa.Column('included_sms_units_snapshot', sa.Integer(), nullable=True),
    sa.Column('overage_price_per_sms_kes_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_subscriptions_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'superadmin', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_users_client_account_id_client_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_id_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'completed', 'failed', name='campaign_status'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_campaigns_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_campaigns_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id_id'], ['sender_ids.id'], name=op.f('fk_campaigns_sender_id_id_sender_ids'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_opted_out', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_contacts_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_contacts_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('topup', 'deduction', 'refund', 'adjustment', name='credit_tx_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_credit_transactions_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_credit_transactions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions'))
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_groups_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_groups_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('group_contacts',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_group_contacts_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_contacts_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'contact_id', name=op.f('pk_group_contacts'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', name='message_status'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_messages_contact_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('group_contacts')
    op.drop_table('groups')
    op.drop_table('credit_transactions')
    op.drop_table('contacts')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('sender_ids')
    op.drop_table('plans')
    op.drop_table('client_accounts')
    # ### end Alembic commands ###
