"""mpesa/payment idempotency fields

Revision ID: f5cfac37dadd
Revises: 4871d3fcee9c
Create Date: 2025-12-30 09:36:57.692400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cfac37dadd'
down_revision = '4871d3fcee9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_stk_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=80), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('amount_kes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='mpesa_stk_request_status'), nullable=False),
    sa.Column('mpesa_receipt', sa.String(length=40), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('raw_callback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('fk_mpesa_stk_requests_client_account_id_client_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_mpesa_stk_requests_invoice_id_invoices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mpesa_stk_requests'))
    )
    with op.batch_alter_table('mpesa_stk_requests', schema=None) as batch_op:
        batch_op.create_index('ix_mpesa_stk_client_status', ['client_account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_merchant_request_id'), ['merchant_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_mpesa_receipt'), ['mpesa_receipt'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_result_code'), ['result_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_stk_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.create_index('ix_payments_client_status', ['client_account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_merchant_request_id'), ['merchant_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_unique_constraint('uq_payment_client_checkout', ['client_account_id', 'checkout_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_client_checkout', type_='unique')
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_method'))
        batch_op.drop_index(batch_op.f('ix_payments_merchant_request_id'))
        batch_op.drop_index('ix_payments_client_status')
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')

    with op.batch_alter_table('mpesa_stk_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_status'))
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_result_code'))
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_mpesa_receipt'))
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_merchant_request_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_client_account_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_stk_requests_checkout_request_id'))
        batch_op.drop_index('ix_mpesa_stk_client_status')

    op.drop_table('mpesa_stk_requests')
    # ### end Alembic commands ###
